use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Meta {
    format_version: u32,
    distro: String,
    program: String,
    version: String,
    #[serde(rename = "OS")]
    os: String,
    arch: String,
    profile: bool,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct LayerInfo {
    pub total_solid_area: f32,
    pub largest_area: f32,
    pub smallest_area: f32,
    pub min_x: u32,
    pub min_y: u32,
    pub max_x: u32,
    pub max_y: u32,
    pub area_count: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Plate {
    #[serde(rename = "PlateID")]
    plate_id: u32,
    #[serde(rename = "ProfileID")]
    profile_id: u32,
    created_date: u32,
    stop_layers: String,
    path: String,
    low_quality_layer_number: u32,
    auto_center: u32,
    updated: u32,
    last_print: u32,
    print_time: u32,
    print_est: u32,
    image_rotate: u32,
    mask_effect: u32,
    x_res: u32,
    y_res: u32,
    z_res: u32,
    multi_cure: String,
    multi_thickness: String,
    offset: u32,
    risky: bool,
    is_faulty: bool,
    repaired: bool,
    corrupted: bool,
    total_solid_area: f32,
    layers_count: u32,
    feedback: bool,
    re_slice_needed: bool,
    multi_material: bool,
    #[serde(rename = "PrintID")]
    print_id: u32,
    #[serde(rename = "MC")]
    mc: PlateMc,
    x_min: f32,
    x_max: f32,
    y_min: f32,
    y_max: f32,
    z_min: f32,
    z_max: f32,
}

#[derive(Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PlateMc {
    start_x: u32,
    start_y: u32,
    width: u32,
    height: u32,
    multi_cure_gap: u32,
    count: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Slicer {
    pub _type: String,
    #[serde(rename = "URL")]
    pub url: String,
    pub p_width: u32,
    pub p_height: u32,
    pub scale_factor: u32,
    pub start_layer: u32,
    pub support_depth: u32,
    pub support_layer_number: u32,
    pub thickness: u32,
    pub x_offset: u32,
    pub y_offset: u32,
    pub z_offset: u32,
    pub x_pixel_size: f32,
    pub y_pixel_size: f32,
    // mask: null,
    pub slice_from_zero: bool,
    pub disable_validator: bool,
    pub auto_center: u32,
    pub preview_generate: bool,
    pub running: bool,
    pub debug: bool,
    pub is_faulty: bool,
    pub corrupted: bool,
    pub multi_material: bool,
    pub adapt_export: String,
    pub preview_color: String,
    // faulty_layers: [],
    // overhang_layers: [],
    // layer_status: [],
    // "Boundary": {
    //   "XMin": -71.72,
    //   "XMax": 71.73,
    //   "YMin": -31.39,
    //   "YMax": 31.42,
    //   "ZMin": 0,
    //   "ZMax": 97
    // },
    #[serde(rename = "MC")]
    pub mc: PlateMc,
    pub multi_thickness: String,
    pub export_path: String,
    pub network_save: String,
    pub file: String,
    pub file_size: u32,
    pub adapt_slicing: u32,
    pub adapt_slicing_min: u32,
    pub adapt_slicing_max: u32,
    pub support_offset: u32,
    pub offset: u32,
    pub fill_color: String,
    pub blank_color: String,
    pub dim_amount: u32,
    pub dim_wall: u32,
    pub dim_skip: u32,
    pub pixel_diming: u32,
    pub hatching_type: u32,
    pub elephant_mid_exposure: u32,
    pub elephant_type: u32,
    pub elephant_amount: u32,
    pub elephant_wall: u32,
    pub elephant_layers: u32,
    pub hatching_wall: u32,
    pub hatching_gap: u32,
    pub hatching_outer_wall: u32,
    pub hatching_top_cap: u32,
    pub hatching_bottom_cap: u32,
    pub multi_cure_gap: u32,
    pub anti_alias: u32,
    pub anti_alias_3_d: u32,
    pub anti_alias_3_d_distance: u32,
    pub anti_alias_3_d_min: u32,
    pub anti_alias_threshold: u32,
    pub image_rotate: u32,
    pub ignore_mask: u32,
    #[serde(rename = "XYRes")]
    pub xy_res: u32,
    pub x_res: u32,
    pub y_res: u32,
    pub z_res_perc: u32,
    pub preview_width: u32,
    pub preview_height: u32,
    pub barrel_factor: u32,
    pub barrel_x: u32,
    pub barrel_y: u32,
    pub image_mirror: u32,
    pub display_controller: u32,
    pub light_output_formula: String,
    #[serde(rename = "PlateID")]
    pub plate_id: u32,
    #[serde(rename = "LayerID")]
    pub layer_id: u32,
    pub layer_count: u32,
    #[serde(rename = "UUID")]
    pub uuid: String,
    // dynamic_thickness: [],
    #[serde(rename = "FillColorRGB")]
    pub fill_color_rgb: Color,
    #[serde(rename = "BlankColorRGB")]
    pub blank_color_rgb: Color,
    pub export_type: u32,
    pub output_path: String,
    pub suffix: String,
    pub skip_empty: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Color {
    r: u32,
    g: u32,
    b: u32,
    a: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Profile {
    #[serde(rename = "ResinID")]
    resin_id: u32,
    #[serde(rename = "ProfileID")]
    profile_id: u32,
    title: String,
    desc: String,
    color: String,
    resin_price: u32,
    optimum_temperature: u32,
    depth: u32,
    support_top_wait: u32,
    support_wait_height: u32,
    support_depth: u32,
    support_wait_before_print: u32,
    support_wait_after_print: u32,
    transitional_layer: u32,
    updated: u32,
    custom_values: ProfileCustomValues,
    _type: u32,
    z_step_wait: u32,
    top_wait: u32,
    wait_height: u32,
    cure_time: u32,
    wait_before_print: u32,
    wait_after_print: u32,
    support_cure_time: u32,
    pub support_layer_number: u32,
    adapt_slicing: u32,
    adapt_slicing_min: u32,
    adapt_slicing_max: u32,
    support_offset: u32,
    offset: u32,
    fill_color: String,
    blank_color: String,
    dim_amount: u32,
    dim_wall: u32,
    dim_skip: u32,
    pixel_diming: u32,
    hatching_type: u32,
    elephant_mid_exposure: u32,
    elephant_type: u32,
    elephant_amount: u32,
    elephant_wall: u32,
    elephant_layers: u32,
    hatching_wall: u32,
    hatching_gap: u32,
    hatching_outer_wall: u32,
    hatching_top_cap: u32,
    hatching_bottom_cap: u32,
    multi_cure_gap: u32,
    anti_alias: u32,
    anti_alias_3_d: u32,
    anti_alias_3_d_distance: u32,
    anti_alias_3_d_min: u32,
    anti_alias_threshold: u32,
    image_rotate: u32,
    ignore_mask: u32,
    #[serde(rename = "XYRes")]
    xy_res: u32,
    y_res: u32,
    z_res_perc: u32,
    dynamic_cure_time: String,
    dynamic_speed: String,
    shield_before_layer: String,
    shield_after_layer: String,
    shield_during_cure: String,
    shield_start: String,
    shield_resume: String,
    shield_finish: String,
    laser_code: String,
    shutter_open_gcode: String,
    shutter_close_gcode: String,
    separation_detection: String,
    resin_level_detection: String,
    crash_detection: String,
    dynamic_wait: String,
    slow_section_height: u32,
    slow_section_step_wait: u32,
    jump_per_layer: u32,
    dynamic_wait_after_lift: String,
    dynamic_lift: String,
    jump_height: u32,
    low_quality_cure_time: u32,
    low_quality_skip_per_layer: u32,
    #[serde(rename = "XYResPerc")]
    xy_res_perc: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ProfileCustomValues {
    cd_threshold: String,
    dw_flow_end_slope: String,
    fss_enable_crashdetection: String,
    fss_enable_dynamicwait: String,
    fss_enable_peeldetection: String,
    fss_enable_resinleveldetection: String,
    pd_peel_end_slope: String,
    pd_peel_start_slope: String,
    resin_preheat_temperature: String,
    rl_threshold: String,
    uv_pwm_value: String,
}

impl Default for Meta {
    fn default() -> Self {
        Self {
            format_version: 2,
            distro: "generic".into(),
            program: "mslicer".into(),
            version: Default::default(),
            os: Default::default(),
            arch: Default::default(),
            profile: false,
        }
    }
}

impl Default for Plate {
    fn default() -> Self {
        Self {
            plate_id: Default::default(),
            profile_id: Default::default(),
            created_date: Default::default(),
            stop_layers: Default::default(),
            path: Default::default(),
            low_quality_layer_number: Default::default(),
            auto_center: Default::default(),
            updated: Default::default(),
            last_print: Default::default(),
            print_time: Default::default(),
            print_est: Default::default(),
            image_rotate: Default::default(),
            mask_effect: Default::default(),
            x_res: Default::default(),
            y_res: Default::default(),
            z_res: Default::default(),
            multi_cure: Default::default(),
            multi_thickness: Default::default(),
            offset: Default::default(),
            risky: Default::default(),
            is_faulty: Default::default(),
            repaired: Default::default(),
            corrupted: Default::default(),
            total_solid_area: Default::default(),
            layers_count: Default::default(), // ←
            feedback: Default::default(),
            re_slice_needed: Default::default(),
            multi_material: Default::default(),
            print_id: Default::default(),
            mc: Default::default(),
            x_min: Default::default(), // ←
            x_max: Default::default(), // ←
            y_min: Default::default(), // ←
            y_max: Default::default(), // ←
            z_min: Default::default(), // ←
            z_max: Default::default(), // ←
        }
    }
}

impl Default for Slicer {
    fn default() -> Self {
        Self {
            _type: "stl".into(),
            url: "".into(),
            p_width: Default::default(),  // ←
            p_height: Default::default(), // ←
            scale_factor: 0,
            start_layer: 0,
            support_depth: 50,
            support_layer_number: 3,
            thickness: 50,
            x_offset: Default::default(), // ←
            y_offset: Default::default(), // ←
            z_offset: 0,
            x_pixel_size: Default::default(), // ←
            y_pixel_size: Default::default(), // ←
            slice_from_zero: false,
            disable_validator: false,
            auto_center: 0,
            preview_generate: false,
            running: false,
            debug: false,
            is_faulty: false,
            corrupted: false,
            multi_material: false,
            adapt_export: "".into(),
            preview_color: "".into(),
            mc: Default::default(),
            multi_thickness: "".into(),
            export_path: "".into(),
            network_save: "".into(),
            file: Default::default(), // ←
            file_size: 0,
            adapt_slicing: 0,
            adapt_slicing_min: 0,
            adapt_slicing_max: 0,
            support_offset: 0,
            offset: 0,
            fill_color: "#ffffff".into(),
            blank_color: "#000000".into(),
            dim_amount: 0,
            dim_wall: 0,
            dim_skip: 0,
            pixel_diming: 0,
            hatching_type: 0,
            elephant_mid_exposure: 1,
            elephant_type: 0,
            elephant_amount: 0,
            elephant_wall: 0,
            elephant_layers: 0,
            hatching_wall: 20,
            hatching_gap: 20,
            hatching_outer_wall: 20,
            hatching_top_cap: 10,
            hatching_bottom_cap: 10,
            multi_cure_gap: 0,
            anti_alias: 1,
            anti_alias_3_d: 0,
            anti_alias_3_d_distance: 0,
            anti_alias_3_d_min: 0,
            anti_alias_threshold: 0,
            image_rotate: 0,
            ignore_mask: 1,
            xy_res: 0,
            x_res: 0,
            y_res: 0,
            z_res_perc: 0,
            preview_width: Default::default(),  // ←
            preview_height: Default::default(), // ←
            barrel_factor: 0,
            barrel_x: 0,
            barrel_y: 0,
            image_mirror: 1,
            display_controller: 1,
            light_output_formula: "".into(),
            plate_id: 0,
            layer_id: 0,
            layer_count: Default::default(), // ←
            uuid: "".into(),
            fill_color_rgb: Color {
                r: 255,
                g: 255,
                b: 255,
                a: 255,
            },
            blank_color_rgb: Color {
                r: 0,
                g: 0,
                b: 0,
                a: 255,
            },
            export_type: 1,
            output_path: "".into(),
            suffix: "".into(),
            skip_empty: 0,
        }
    }
}

impl Default for Profile {
    fn default() -> Self {
        Self {
            resin_id: 0,
            profile_id: 0,
            title: "Unknown".into(),
            desc: "".into(),
            color: "".into(),
            resin_price: 0,
            optimum_temperature: 0,
            depth: 50,
            support_top_wait: 0,
            support_wait_height: 5,
            support_depth: 50,
            support_wait_before_print: 1,
            support_wait_after_print: 0,
            transitional_layer: 10,
            updated: Default::default(), // <-
            custom_values: ProfileCustomValues {
                cd_threshold: "2000".into(),
                dw_flow_end_slope: "10".into(),
                fss_enable_crashdetection: "0".into(),
                fss_enable_dynamicwait: "0".into(),
                fss_enable_peeldetection: "0".into(),
                fss_enable_resinleveldetection: "0".into(),
                pd_peel_end_slope: "0".into(),
                pd_peel_start_slope: "0".into(),
                resin_preheat_temperature: "25".into(),
                rl_threshold: "-5".into(),
                uv_pwm_value: "1".into(),
            },
            _type: 0,
            z_step_wait: 5000,
            top_wait: 0,
            wait_height: 5,
            cure_time: 3,
            wait_before_print: 1,
            wait_after_print: 0,
            support_cure_time: 30,
            support_layer_number: 3,
            adapt_slicing: 0,
            adapt_slicing_min: 0,
            adapt_slicing_max: 0,
            support_offset: 0,
            offset: 0,
            fill_color: "#ffffff".into(),
            blank_color: "#000000".into(),
            dim_amount: 0,
            dim_wall: 0,
            dim_skip: 0,
            pixel_diming: 0,
            hatching_type: 0,
            elephant_mid_exposure: 1,
            elephant_type: 0,
            elephant_amount: 0,
            elephant_wall: 0,
            elephant_layers: 0,
            hatching_wall: 20,
            hatching_gap: 20,
            hatching_outer_wall: 20,
            hatching_top_cap: 10,
            hatching_bottom_cap: 10,
            multi_cure_gap: 0,
            anti_alias: 1,
            anti_alias_3_d: 0,
            anti_alias_3_d_distance: 0,
            anti_alias_3_d_min: 0,
            anti_alias_threshold: 0,
            image_rotate: 0,
            ignore_mask: 1,
            xy_res: 0,
            y_res: 0,
            z_res_perc: 0,
            dynamic_cure_time: "".into(),
            dynamic_speed: "".into(),
            shield_before_layer: "G90\\r\\nSET_PROGRESS_BAR CL=[[LayerNumber]] TL=[[TotalNumberOfLayers]]\\r\\nMOVE_PLATE Z=[[LayerPosition]] F=600\\r\\n[[MoveWait 2]]\\r\\n[[PositionSet [[LayerPosition]]]]\\r\\n[JS]\\r\\nif([[_FssEnableDynamicwait]] == 0)output=\\\"[[DynamicWaitStart]]\\\";\\r\\n[/JS]\\r\\nfss_idle".into(),
            shield_after_layer: "[JS]if ([[LayerNumber]]==1||[[LayerNumber]]%3==0) output=\\\"TRIGGER\\\";[/JS]\\r\\n[JS]if ([[LayerNumber]]==1||[[LayerNumber]]%5==0) output=\\\"M105\\\";[/JS]\\r\\n[[MoveCounterSet 0]]\\r\\nUVLED_ON PWM=[[_UvPwmValue]]\\r\\nDWELL P={[[CureTime]]*1000}\\r\\n[[MoveWait 1]]\\r\\nUVLED_OFF \\r\\n[[GPIOHigh 10]]\\r\\n\\r\\n[JS]\\r\\nvar nano = nanodlpContext();\\r\\nvar resinlevel = nano[\\\"Status\\\"][\\\"ResinLevelMm\\\"];\\r\\nif( [[_FssEnablePeeldetection]]==0 \\u0026\\u0026 [[CurrentPosition]] \\u003e resinlevel) output=\\\"[[SeparationDetectionStart]]\\\";\\r\\n[/JS]\\r\\n\\r\\n[[MoveCounterSet 0]]\\r\\nG91\\r\\nMOVE_PLATE_FSS Z=[[ZLiftDistance]] F={120-([[LayerNumber]]\\u003c5)*70}\\r\\n[[PositionChange [[ZLiftDistance]]]]\\r\\n[[MoveWait 1]]\\r\\n[[SeparationDetectionStop]]\\r\\n[JS]if ([[LayerNumber]]==1||[[LayerNumber]]%100==0) output=\\\"G4 P2000\\\";[/JS]\\r\\n[JS]if ([[LayerNumber]]==1||[[LayerNumber]]%100==0) output=\\\"[[PressureWrite 1]]\\\";[/JS]".into(),
            shield_during_cure: "".into(),
            shield_start: "".into(),
            shield_resume: "".into(),
            shield_finish: "".into(),
            laser_code: "".into(),
            shutter_open_gcode: "".into(),
            shutter_close_gcode: "".into(),
            separation_detection: "".into(),
            resin_level_detection: "".into(),
            crash_detection: "".into(),
            dynamic_wait: "".into(),
            slow_section_height: 7,
            slow_section_step_wait: 40,
            jump_per_layer: 0,
            dynamic_wait_after_lift: "".into(),
            dynamic_lift: "".into(),
            jump_height: 0,
            low_quality_cure_time: 0,
            low_quality_skip_per_layer: 0,
            xy_res_perc: 0,
        }
    }
}
