struct SizedString<const SIZE: usize> {
    data: [u8; SIZE],
}

struct PreviewImage<const WIDTH: usize, const HEIGHT: usize> {
    data: [[u16; WIDTH]; HEIGHT],
}

struct HeaderInfo {
    pub version: SizedString<4>,
    // Magic Tag (0x07, 0x00, 0x00, 0x00, 0x44, 0x4C, 0x50, 0x00)
    pub software_info: SizedString<32>,
    pub software_version: SizedString<24>,
    pub file_time: SizedString<24>,
    pub printer_name: SizedString<32>,
    pub printer_type: SizedString<32>,
    pub profile_name: SizedString<32>,
    pub anti_aliasing_level: u16,
    pub grey_level: u16,
    pub blur_level: u16,
    pub small_preview: PreviewImage<116, 116>,
    // Fixed string "0xd, 0xa"
    pub big_preview: PreviewImage<290, 290>,
    // Fixed string "0xd, 0xa"
    pub layer_count: u32,
    pub x_resolution: u16,
    pub y_resolution: u16,
    pub x_mirror: bool,
    pub y_mirror: bool,
    pub x_size: f32,
    pub y_size: f32,
    pub z_size: f32,
    pub layer_thickness: f32,
    pub exposure_time: f32,
    pub exposure_delay_mode: bool,
    pub turn_off_time: f32,
    pub bottom_before_lift_time: f32,
    pub bottom_after_lift_time: f32,
    pub bottom_after_retract_time: f32,
    pub before_lift_time: f32,
    pub after_lift_time: f32,
    pub after_retract_time: f32,
    pub bottom_exposure_time: f32,
    pub bottom_layers: u32,
    pub bottom_lift_distance: f32,
    pub bottom_lift_speed: f32,
    pub lift_distance: f32,
    pub lift_speed: f32,
    pub bottom_retract_distance: f32,
    pub bottom_retract_speed: f32,
    pub second_retract_distance: f32,
    pub second_retract_speed: f32,
    pub bottom_light_pwm: u16,
    pub light_pwm: u16,
    pub advanced_mode: bool,
    pub printing_time: u32,
    pub total_volume: f32,
    pub total_weight: f32,
    pub total_price: f32,
    pub price_unit: SizedString<8>,
    pub offset_of_layer_content: u32,
    pub grey_scale_level: bool,
    pub transition_layers: u16,
}

struct LayerContent {
    pub pause_flag: u16,
    pub pause_position_z: f32,
    pub layer_position_z: f32,
    pub layer_exposure_time: f32,
    pub layer_off_time: f32,
    pub before_lift_time: f32,
    pub after_lift_time: f32,
    pub after_retract_time: f32,
    pub lift_distance: f32,
    pub lift_speed: f32,
    pub second_lift_distance: f32,
    pub second_lift_speed: f32,
    pub retract_distance: f32,
    pub retract_speed: f32,
    pub second_retract_distance: f32,
    pub second_retract_speed: f32,
    pub light_pwm: u16,
    // Fixed string "0xd, 0xa"
}
