[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytemuck = "1.16.1"
eframe = { version = "0.27.2", features = ["wgpu"] }
egui = "0.27.2"
egui-wgpu = "0.27.2"
wgpu = "0.19.4"

slicer = { path = "../slicer" }
encase = "0.8.0"
nalgebra = "0.32.6"
